### ISSUE TITLE
New fields: event date, and location

### ISSUE THREAD

**Issue by wswtizer** [ibm-watson-data-lab/devcenter#38]
For DSX, we plan on starting to make use of the Event type. For this, we need two new fields:
1. Event date: text field to capture a range like "June 21-25, 2017"
2. Event location: text field to capture text like "Toronto, Canada"

Note that we could make use of the fields for other types, like course, webinar, etc - right now, I work around this for Webinar by adding the date in the title...

Thanks @glynnbird  :)

**Comment by glynnbird** [comment]
Added new text fields to the schema:

- event_date
- event_location

**Comment by wswtizer** [comment]
Thank you @glynnbird !
